### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by hustcc** [lint-md/eslint-plugin-lint-md#1]
名称建议：

1. npm 包名称 @lint-md/eslint-plugin
2. 仓库名称 eslint-plugin
3. 相应的 readme 需要修改

工程

1. 去掉 lock 文件
2. peerDependence 是否需要添加 eslint 的版本
3. require 中无需 index
4. 代码文件名使用 xx-yy 的形式（强烈建议，我这边以及我这边团队，都使用这样的规则）

**Comment by yuzhanglong** [comment]
> 名称建议：
> 
> 1. npm 包名称 @lint-md/eslint-plugin
> 2. 仓库名称 eslint-plugin
> 3. 相应的 readme 需要修改
> 
> 工程
> 
> 1. 去掉 lock 文件
> 2. peerDependence 是否需要添加 eslint 的版本
> 3. require 中无需 index
> 4. 代码文件名使用 xx-yy 的形式（强烈建议，我这边以及我这边团队，都使用这样的规则）

收到~
